name: Paul Persky Photography
favicon: null
layout_spectrum: 0
typography_spectrum: 0.3988
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#373332'
    - '#9a8067'
    - '#e0c19d'
    - '#8e403b'
  brandStrength: 0
  lightness: 0
  saturation: 0
  rhythmicContrast: 0.5
purpose:
  - name: shares
    item: null
    url: null
